#CONDIGURAÇÃO DA APRESENTAÇÃO DE ERRO DA APLICAÇÃO NA TELA DO USUÁRIO
server:
  error:
    include-stacktrace: on_param #Esconde o stack tracer de errors apresentados no front-end

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_security?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  main:
    allow-circular-references: true #  é usada para permitir ou proibir a criação de referências circulares entre beans em seu aplicativo Spring
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

